[package]
name = "MyActions"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
grammers-client = "0.7.0"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
