name: 64gram(Js0n)

on:
  workflow_dispatch:

jobs:
  docker:
    name: Ubuntu
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ghcr.io/real-lihua/64gram_js0n/centos_env:latest

    steps:
      - name: Clone.
        uses: actions/checkout@v4
        with:
          repository: JasonKhew96/64gram
          submodules: recursive

      - name: First set up.
        run: |
          sudo apt update
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be

      - name: Docker image build.
        run: |
          cd Telegram/build/docker/centos_env
          rm poetry.lock
          poetry install
          DEBUG= LTO= poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t $IMAGE_TAG -

      - name: Push the Docker image.
        if: ${{ github.ref_name == github.event.repository.default_branch }}
        run: docker push $IMAGE_TAG

  linux:
    name: Rocky Linux 8
    runs-on: ubuntu-latest

    env:
      UPLOAD_ARTIFACT: "true"

    steps:
      - name: Clone.
        uses: actions/checkout@v4
        with:
          repository: JasonKhew96/64gram
          submodules: recursive
        
      - name: Free up some disk space.
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        
      - name: Docker image build.
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          cd Telegram/build/docker/centos_env
          rm poetry.lock
          poetry install
          DEBUG= LTO= poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t tdesktop:centos_env -
