name: telegram_count

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      actions: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - run: gh cache delete telegram_count
      
      - uses: actions/cache/restore@v4
        id: cache
        with:
          key: telegram_count
          path: last_id

      - run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            gh cache delete telegram_count || true
            BOTAPI="https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}"
            id="$(curl "$BOTAPI/sendMessage?chat_id=${{ secrets.CHAT_ID }}&text=正在进行消息计数" | jq .result.message_id)"
            if [ -f last_id ]; then
                last_id="$(cat last_id)"
            else
                last_id=${{ secrets.START_ID }}
            fi
            curl -o /dev/null "$BOTAPI/editMessageText?chat_id=${{ secrets.CHAT_ID }}&message_id=$id&text=$(( id - last_id  ))"
            echo -n $id > last_id
          fi
          
      - uses: actions/cache/save@v4
        with:
          key: telegram_count
          path: last_id
