name: telegram_count

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            id="$(curl "$BOTAPI/sendMessage?chat_id=$CHAT_ID&text=消息计数中" | jq .result.message_id)"
            if [ ! -z "${{ secrets.LAST_ID }}" ]; then
                last_id="${{ secrets.LAST_ID }}"
            else
                last_id=$id
            fi
            curl -o /dev/null "$BOTAPI/editMessageText?chat_id=$CHAT_ID&message_id=$id&text=$(( id - last_id ))"
            gh secret set LAST_ID --body "$id"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          BOTAPI: "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}"
          CHAT_ID: ${{ secrets.CHAT_ID }}
