name: telegram_count

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: id
          key: telegram_count

      - run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            BotApi="https://api.telegram.org/bot${BOT_TOKEN}"
            curl "$BotApi/getMe" | jq
          fi
