name: telegram_count

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        id: cache
        with:
          key: telegram_count
          path: last_id

      - run: |
          if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            BOTAPI="https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}"
            id="$(curl "$BOTAPI/sendMessage?chat_id=-1002025381790&text=正在进行消息计数" | jq .result.message_id)"
            if [ -f last_id ]; then
              last_id="$(cat last_id)"
              curl "$BOTAPI/editMessageText?chat_id=-1002025381790&message_id=$id&text=$(( id - last_id  ))"
            fi
            echo -n $id > last_id
          fi
          
      - uses: actions/cache/save@v4
        if: always()
        with:
          key: ${{ steps.cache.outputs.cache-primary-key }}
          path: last_id
