name: tinyPiXOS
on:
  workflow_dispatch:
jobs:
  build:
    name: deploy to staging
    runs-on: ubuntu-22.04

    steps:
      - name: Clone.
        uses: actions/checkout@v4
        with:
          repository: JTinyPiXOS/tinyPiXCore
      - run: |
              apt install libsdl2-image-dev libsdl2-gfx-dev \
              libcairo2-dev libpango1.0-dev libglib2.0-dev \
              libpangocairo-1.0-0 libfontconfig-dev libfreetype-dev \
              libgbm-dev libgles2 libegl-dev \
              libasound2-dev libjson-c-dev libssl-dev libavcodec-dev libavformat-dev \
              libavutil-dev libswscale-dev libswresample-dev \
              libavfilter-dev libavdevice-dev libssl-dev librsvg2-dev bluez libbluetooth-dev \
              libdbus-1-dev bluez-alsa-utils libasound2-plugin-bluez bluez-obexd  libusb-1.0-0-dev \
              libboost-all-dev libleveldb-dev libmarisa-dev libopencc-dev libyaml-cpp-dev libgoogle-glog-dev
              cmake .
              make
